### PR TITLE
Task #48 MyBitGo Blog

### PR DESCRIPTION
**Pull request by alejodosr**

### CODE REVIEW

**Comment by alejodosr** [comment]
Hi, I tought the process of triggering the MYB token transaction was automatic, but I do not see the transaction on etherscan yet, is there any problem? How are the transactions triggered?

**Comment by jjperezaguinaga** [comment]
Hi @alejodosr , unfortunately you had to name the task "Fixes #48" to [Open Bounty](https://wiki.status.im/Status_Open_Bounty) to work. Apologies for not clarifying this further. In the meantime, I can get your tokens and send it to the address of your like directly.

Please go to https://keybase.io/encrypt, and select "jjperezaguinaga" in _Recipient_. In the text area put your addres in the form `0x12345...` where you want to received your tokens and I'll send them back to you. Thanks!

**Comment by alejodosr** [comment]
Ok @jjperezaguinaga already done. Not sure if I did correctly since the output was an encrypted message. For next contributions I'll take the title issue into account. Thanks.

**Comment by jjperezaguinaga** [comment]
Hi @alejodosr , could you paste the encrypted output in a comment here in Github? Since it's encrypted with my public key, I'll be the only one able to see it. Thanks!

**Comment by alejodosr** [comment]
Sure.

`-----BEGIN PGP MESSAGE-----
Version: Keybase OpenPGP v2.0.80
Comment: https://keybase.io/crypto

wcBMA6gpy0Zv/UOFAQgAjfQxvGfbpXkHX4pX/em7rx/ycFIUt8SW22v5z6pp96DT
9i+NGYRQIkOTMpiV53i2GCNpst3gQTR9G6923z3xI7Tp++Xolouo1fa627wwBFVt
66BHmcjo962KJBwdC9ZkahsvB/R9/d93aavud0j0N2Lcxo+1dEImQGJu1ijFkDbQ
5NTd1QJOON2emMxD7SL3P5gKg2HPlCCx91ohlPgqLAFRbUvou44aCkny6Y4sb9H2
BO+xlOQj0bSUKjxvElw3zybNBFZni22kkGhOvAsTDQ5c65SqJQ/uBKR5MwBmxRqE
40uW3kZzMERN7P8v9Ve6XWykPSlKkeuca9w7Az6ZJdJmAbXOlZhhzW2c/i9rYL63
iWwkG4N9xVkUe6CHhayMEjp8ajlvg3RpgNNnGG/OX+5yAWxU/0EEHWbjK7vhp3xa
25nImmCPoQ9/jpxkKtGhzZf2Secp6jmXr+YxsFdp2uJUSrmYkEyM
=OgdF
-----END PGP MESSAGE-----`

**Comment by alejodosr** [comment]
Sure.

-----BEGIN PGP MESSAGE-----
Version: Keybase OpenPGP v2.0.80
Comment: https://keybase.io/crypto

wcBMA6gpy0Zv/UOFAQgAjfQxvGfbpXkHX4pX/em7rx/ycFIUt8SW22v5z6pp96DT
9i+NGYRQIkOTMpiV53i2GCNpst3gQTR9G6923z3xI7Tp++Xolouo1fa627wwBFVt
66BHmcjo962KJBwdC9ZkahsvB/R9/d93aavud0j0N2Lcxo+1dEImQGJu1ijFkDbQ
5NTd1QJOON2emMxD7SL3P5gKg2HPlCCx91ohlPgqLAFRbUvou44aCkny6Y4sb9H2
BO+xlOQj0bSUKjxvElw3zybNBFZni22kkGhOvAsTDQ5c65SqJQ/uBKR5MwBmxRqE
40uW3kZzMERN7P8v9Ve6XWykPSlKkeuca9w7Az6ZJdJmAbXOlZhhzW2c/i9rYL63
iWwkG4N9xVkUe6CHhayMEjp8ajlvg3RpgNNnGG/OX+5yAWxU/0EEHWbjK7vhp3xa
25nImmCPoQ9/jpxkKtGhzZf2Secp6jmXr+YxsFdp2uJUSrmYkEyM
=OgdF
-----END PGP MESSAGE-----

**Comment by jjperezaguinaga** [comment]
Great! The MYB tokens should be in their way, thanks again!

**Pull request merged**
