### PR TITLE
Fixes #26

### LINKED ISSUE #26: Write blog about the value of Go
We need a blog written showcasing the value of MyBit Go over traditional investment funds. 

Requirements:
1. Must be easy to understand for people without a technical background
2. limit the use of blockchain technology and vocabulary
3. clearly describe value points and competitive advantages

Resources:
go.mybit.io/app
https://files.mybit.io/files/

Expected Deliverables:
Final document in English in .doc or .docx format.
Distribution on your own personal medium and/or steemit account and promotion on your social channels

Additional Information:
The creative process often involves multiple iterations. Therefore, please do not expect the task to be closed after the first version is submitted. We do understand the value of every contributors time, which is why we strive to make the task descriptions as detailed as possible. If you are unsure about a specific detail or have any questions please feel free to ask prior to starting or during the process.

Disclaimer: 
All work completed via the MyBit Decentralised Development Fund is property of the MyBit Foundation (CHE-177.186.963) and may be used, re-used, and/or distributed, re-distributed by the MyBit Foundation for financial gain. The contributor holds no warrant nor claims for any future payments resulting from monetisation schemes originating from the MyBit Foundation or any of its affiliates. Where law permits outside of open source regulations, the contributor is not permitted to distribute any work completed via the MyBit Decentralised Development Fund (DDF) for personal gain.

### PR DESCRIPTION
**Pull request by rd123myb**

### CODE REVIEW

**Comment by rd123myb** [comment]
Hey this is what i submitted for review its for task #26  to describe the value of mybit go

**Comment by rd123myb** [comment]
and it says #49 below it
there are two files in the request,  the file for review is the bottom one submitted 20 days ago called '#26 Value of Mybit Go - Rory.docx'

**Comment by cryptnotiq** [comment]
hey @rd123myb could you create new and paste the text into a document and submit a new pull request. The uploading doesn't seem to be working.

**Comment by rd123myb** [comment]
ok i put in a google doc as it seemed to be easier to read does that suit? i see it in my commit section so i think it worked (sorry i'm still figuring out github)

**Comment by cryptnotiq** [comment]
hey @rd123myb I requested edit access to the docs so I can comment on them.

**Comment by rd123myb** [comment]
whoops! got it added now

**Comment by cryptnotiq** [comment]
hey @rd123myb both look good, can you go ahead and submit pull requests?

**Comment by jjperezaguinaga** [comment]
👋 @rd123myb do you have an Open Bounty account? Open Bounty doesn't seem to pick up your address for payment.

**Comment by rd123myb** [comment]
Hi @jjperezaguinaga 👋 , sorry for the late reply - i did setup an account with an eth address assigned (rd123myb) just checked then and has my correct payment details there but im new so might be missing a step?

**Comment by jjperezaguinaga** [comment]
@rd123myb this one was paid properly, going to check the other ones, thank you!

**Pull request merged**
