### PR TITLE
Fixes #34, Fixes #35

### LINKED ISSUE #34: Case Study, Remittance Market US-Mexico and BTMs
We need a case study written regarding the remittance market between Mexico and NA and how Bitcoin ATMs could fit into the picture to provide a more flexible and cost-effective solution for international money transfers.

Requirements:
1. Must include sourced data regarding the remittance market
2. Must include sourced data of the Bitcoin ATM market
3. Must tie points 1 and 2 together to make a claim about how Bitcoin ATMs can be a viable tool for enhancing the remittance market between the US and Mexico.

Resources:
mybit.io
https://files.mybit.io/files/

Expected Deliverables:
Final document in English in .doc or .docx format.
Distribution on your own personal medium and/or steemit account and promotion on your social channels

Additional Information:
The creative process often involves multiple iterations. Therefore, please do not expect the task to be closed after the first version is submitted. We do understand the value of every contributors time, which is why we strive to make the task descriptions as detailed as possible. If you are unsure about a specific detail or have any questions please feel free to ask prior to starting or during the process.

Disclaimer: 
All work completed via the MyBit Decentralised Development Fund is property of the MyBit Foundation (CHE-177.186.963) and may be used, re-used, and/or distributed, re-distributed by the MyBit Foundation for financial gain. The contributor holds no warrant nor claims for any future payments resulting from monetisation schemes originating from the MyBit Foundation or any of its affiliates. Where law permits outside of open source regulations, the contributor is not permitted to distribute any work completed via the MyBit Decentralised Development Fund (DDF) for personal gain.

### LINKED ISSUE #35: Case study, VR arcade research in Asia
We need a case study written regarding the virtual reality market and the arcade market in Asia. This should result in the convergence of an opportunity for VR arcades in Asia Markets.

Requirements:
1. Must include sourced data regarding the VR market
2. Must include sourced data of the arcade market in asia
3. Must tie points 1 and 2 together to make a claim about how VR can be a viable solution for enhancing the arcade experience in Asia.

Resources:
mybit.io
https://files.mybit.io/files/

Expected Deliverables:
Final document in English in .doc or .docx format.
Distribution on your own personal medium and/or steemit account and promotion on your social channels

Additional Information:
The creative process often involves multiple iterations. Therefore, please do not expect the task to be closed after the first version is submitted. We do understand the value of every contributors time, which is why we strive to make the task descriptions as detailed as possible. If you are unsure about a specific detail or have any questions please feel free to ask prior to starting or during the process.

Disclaimer: 
All work completed via the MyBit Decentralised Development Fund is property of the MyBit Foundation (CHE-177.186.963) and may be used, re-used, and/or distributed, re-distributed by the MyBit Foundation for financial gain. The contributor holds no warrant nor claims for any future payments resulting from monetisation schemes originating from the MyBit Foundation or any of its affiliates. Where law permits outside of open source regulations, the contributor is not permitted to distribute any work completed via the MyBit Decentralised Development Fund (DDF) for personal gain.

### PR DESCRIPTION
**Pull request by uivlis**

### CODE REVIEW

**Comment by jjperezaguinaga** [comment]
@uivlis Thank you!

**Comment by uivlis** [comment]
Hey, @jjperezaguinaga, for some reason or another, one of the bounties is stuck on status "payout pending maintainer confirmation" for 2 days straight. Is there anything on your side you can do to speed it up?

**Comment by jjperezaguinaga** [comment]
@uivlis weird! We had a couple issues with Open Bounty. The good thing is that they are smart contracts so I can execute them myself manually. Which one are you missing?

**Comment by uivlis** [comment]
The US-Mexico case study.
I dwelled into the problem (on reddit...). Apparently, if you send the bounty with too little a gas, it takes a lot more to execute.

**Comment by jjperezaguinaga** [comment]
Done! https://etherscan.io/tx/0x3af3e655112bbf6dac3fb1cc2aae00b1dc5ab7d9404634016edfc8ad156a4acb

**Pull request merged**
